name: Multi-Image Build

on:
  push:
    branches:
    # - develop
      - feature/CICD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Add steps to install Python dependencies and build Python app
      # Replace this with actual steps for your Python app
      - name: Checking List . python compiling Files
        run: ls -ltrah . && ls -ltrah backend_drf/src

      # Caching for Python dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend_drf/src/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build and push Python Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend_drf/src
          file: ./backend_drf/src/Dockerfile
          push: true
          tags: careyourspets/equipo-4-backend:stage-django-latest

      # Setup Node.js and NestJS
      - name: Setup Node.js and NestJS
        uses: actions/setup-node@v2
        with:
          node-version: "18"
        
      - run: npm install -g @nestjs/cli

      - name: Checking List . nestjs compiling Files
        run: ls -ltrah . && ls -ltrah users/src

      # Caching for NestJS dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('users/src/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build and push NestJS Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./users
          file: ./users/Dockerfile
          push: true
          tags: careyourspets/equipo-4-backend:stage-nestjs-latest